/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package automatedpayrollsystem;

import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Jomax
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
    // Check if CSV file loaded properly
    try {
        EmployeeDataLoader loader = new EmployeeDataLoader("MotorPH_Employee_Data2.csv");
        if (loader.getAllEmployees().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A CSV loaded but no employee data found.",
                "CSV File Check", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "✅ Successfully loaded employee data from CSV!",
                "CSV File Check", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Failed to load CSV file:\n" + e.getMessage(),
            "CSV File Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JUsernameTextField = new javax.swing.JTextField();
        rolecombobox = new javax.swing.JComboBox<>();
        Cancel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ForgotPasswordorUsernameMouseClick = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        Login = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 99, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 99, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabel5.setText("Select Position:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 140, -1));

        JUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(JUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 180, -1));

        rolecombobox.setBackground(new java.awt.Color(0, 172, 238));
        rolecombobox.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Personnel", "Team Leader", "Payroll Manager", "Accounting Head", "Regular Employee" }));
        getContentPane().add(rolecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, -1));

        Cancel.setBackground(new java.awt.Color(0, 172, 238));
        Cancel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 122, -1));

        jButton3.setBackground(new java.awt.Color(0, 172, 238));
        jButton3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabel1.setText("Motor PH Payroll System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 320, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 21)); // NOI18N
        jLabel2.setText("By: Jomax");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2410, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setText("Please enter your username and password\t");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 330, -1));

        ForgotPasswordorUsernameMouseClick.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ForgotPasswordorUsernameMouseClick.setText("Forgot Password or Username");
        ForgotPasswordorUsernameMouseClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPasswordorUsernameMouseClickMouseClicked(evt);
            }
        });
        getContentPane().add(ForgotPasswordorUsernameMouseClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 180, -1));
        setJMenuBar(Login);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUsernameTextFieldActionPerformed

    private void ForgotPasswordorUsernameMouseClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPasswordorUsernameMouseClickMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgotPasswordorUsernameMouseClickMouseClicked

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
    System.exit(0); // closes the application
    }//GEN-LAST:event_CancelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String username = JUsernameTextField.getText().trim();
    String password = new String(jPasswordField.getPassword()).trim();
    String role = rolecombobox.getSelectedItem().toString().trim();

    EmployeeDataLoader loader = new EmployeeDataLoader("MotorPH_Employee_Data2.csv");
    List<Employee> allEmployees = loader.getAllEmployees();

    boolean found = false;
    for (Employee emp : allEmployees) {
        if (emp.username.equals(username) && emp.password.equals(password) && emp.role.equalsIgnoreCase(role)) {
            found = true;
            JOptionPane.showMessageDialog(this, "✅ Login successful as " + role);
            
            // Example: open HRDashboard
            if (role.equalsIgnoreCase("HR Personnel") || role.equalsIgnoreCase("Payroll Manager")) {
                new HRDashboard().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "🔒 Role recognized but no dashboard implemented.");
            }
            break;
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "❌ Invalid username, password, or role.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel ForgotPasswordorUsernameMouseClick;
    private javax.swing.JTextField JUsernameTextField;
    private javax.swing.JMenuBar Login;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JComboBox<String> rolecombobox;
    // End of variables declaration//GEN-END:variables


}
