/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package automatedpayrollsystem;

import automatedpayrollsystem.EmployeeDataLoader;
import automatedpayrollsystem.HRDashboard;
import automatedpayrollsystem.ManageEmployeeForm;
import automatedpayrollsystem.PayrollManagerDashboard;
import automatedpayrollsystem.RankandFileDashboard;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.File;

/**
 *
 * @author Jomax
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
    // Check if CSV file loaded properly
    try {
        EmployeeDataLoader loader = new EmployeeDataLoader();
        if (loader.getAllEmployees().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A CSV loaded but no employee data found.",
                "CSV File Check", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "✅ Successfully loaded employee data from CSV!",
                "CSV File Check", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Failed to load CSV file:\n" + e.getMessage(),
            "CSV File Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JUsernameTextField = new javax.swing.JTextField();
        rolecombobox = new javax.swing.JComboBox<>();
        jCancelButton = new javax.swing.JButton();
        jLoginButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ForgotPasswordorUsernameMouseClick = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        Login = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 99, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 99, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabel5.setText("Select Position:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 140, -1));

        JUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(JUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 180, -1));

        rolecombobox.setBackground(new java.awt.Color(0, 172, 238));
        rolecombobox.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Personnel", "Team Leader", "Payroll Manager", "Accounting Head", "Regular Employee" }));
        getContentPane().add(rolecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, -1));

        jCancelButton.setBackground(new java.awt.Color(0, 172, 238));
        jCancelButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 122, -1));

        jLoginButton.setBackground(new java.awt.Color(0, 172, 238));
        jLoginButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabel1.setText("Motor PH Payroll System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 320, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 21)); // NOI18N
        jLabel2.setText("By: Jomax");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2410, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setText("Please enter your username and password\t");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 330, -1));

        ForgotPasswordorUsernameMouseClick.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ForgotPasswordorUsernameMouseClick.setText("Forgot Password or Username");
        ForgotPasswordorUsernameMouseClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPasswordorUsernameMouseClickMouseClicked(evt);
            }
        });
        getContentPane().add(ForgotPasswordorUsernameMouseClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 180, -1));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 360, 50));
        setJMenuBar(Login);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUsernameTextFieldActionPerformed

    private void ForgotPasswordorUsernameMouseClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPasswordorUsernameMouseClickMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgotPasswordorUsernameMouseClickMouseClicked

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
    System.exit(0); // closes the application
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
File file = new File("MotorPH_Employee_Data2.csv");
System.out.println("File exists: " + file.exists());
System.out.println("Absolute path: " + file.getAbsolutePath());

        
if (rolecombobox.getSelectedItem().toString().equals("HR Personnel")) {
    try {
        BufferedReader reader = new BufferedReader(new FileReader("MotorPH_Employee_Data.csv"));
        String line;
        boolean found = false;

        // Skip header
        reader.readLine();

        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",", -1); // -1 to include empty fields

            if (data.length < 21) continue;

            String username = JUsernameTextField.getText().trim();
            String password = jPasswordField.getText().trim();
            String selectedRole = rolecombobox.getSelectedItem().toString();

            String fileUsername = data[20].trim().replace("\"", "");
            String filePassword = data[19].trim().replace("\"", "");
            String fileRole = data[13].trim().replace("\"", "");
            
                    System.out.println("Trying to match:");
                    System.out.println("Input Username: [" + username + "]");
                    System.out.println("File Username: [" + fileUsername + "]");
                    System.out.println("Input Password: [" + password + "]");
                    System.out.println("File Password: [" + filePassword + "]");
                    System.out.println("Input Role: [" + selectedRole + "]");
                    System.out.println("File Role: [" + fileRole + "]");

            boolean isHRMatch = selectedRole.equals("HR Personnel") &&
                                (fileRole.equals("HR Manager") ||
                                 fileRole.equals("HR Team Leader") ||
                                 fileRole.equals("HR Rank and File"));

            if ((isHRMatch || selectedRole.equals(fileRole)) &&
                username.equals(fileUsername) &&
                password.equals(filePassword)) {

                found = true;
                JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

                // OPEN HRDashboard
                HRDashboard hr = new HRDashboard(username);
                hr.setVisible(true);
                this.setVisible(false);
                break;
            }
        }

        reader.close();

        if (!found) {
            JOptionPane.showMessageDialog(this, "Invalid login credentials.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    }//GEN-LAST:event_jLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgotPasswordorUsernameMouseClick;
    private javax.swing.JTextField JUsernameTextField;
    private javax.swing.JMenuBar Login;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JComboBox<String> rolecombobox;
    // End of variables declaration//GEN-END:variables
}